version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build
    working_directory:
      ~/app
    steps:
      - checkout

      - restore_cache:
          keys:
            - stack-work-cache-{{ arch }}

      - run: |
          cp /usr/lib/gcc/x86_64-linux-gnu/5/crtbeginT.o /usr/lib/gcc/x86_64-linux-gnu/5/crtbeginT.o.orig
          cp /usr/lib/gcc/x86_64-linux-gnu/5/crtbeginS.o /usr/lib/gcc/x86_64-linux-gnu/5/crtbeginT.o

          stack config set system-ghc --global true
          stack --local-bin-path ~/app/bin install --ghc-options '-optl-static -fPIC'

      - save_cache:
          key: stack-work-cache-{{ arch }}
          paths:
            - ~/app/.stack-work/

      - store_artifacts:
          path: ~/app/bin
