version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build
    working_directory:
      ~/app
    steps:
      - checkout

      - restore_cache:
          keys:
            - stack-work-cache-{{ arch }}

      - run: |
          stack config set system-ghc --global true
          stack --local-bin-path ~/app/bin install --ghc-options '-optl-static -fPIC'
          docker build -t yesod-heroku .

      - save_cache:
          key: stack-work-cache-{{ arch }}
          paths:
            - ~/app/.stack-work/

      - store_artifacts:
          path: ~/app/bin
