version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build
    working_directory:
      ~/app
    steps:
      - checkout

      - restore_cache:
          keys:
            - stack-work-cache-{{ arch }}
            - stack-cache-{{ arch }}

      - run: |
          cp /usr/lib/gcc/x86_64-linux-gnu/5/crtbeginT.o /usr/lib/gcc/x86_64-linux-gnu/5/crtbeginT.o.orig
          cp /usr/lib/gcc/x86_64-linux-gnu/5/crtbeginS.o /usr/lib/gcc/x86_64-linux-gnu/5/crtbeginT.o

          stack config set system-ghc --global true
          stack --local-bin-path ~/app/dist install --ghc-options '-optl-static -fPIC'

      - save_cache:
          key: stack-work-cache-{{ arch }}
          paths:
            - ~/app/.stack-work/
      - save_cache:
          key: stack-cache-{{ arch }}
          paths:
            - ~/app/.stack/

      - store_artifacts:
          path: ~/app/dist

      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "34:e6:c0:32:7f:74:bf:19:0a:3a:09:52:e6:6e:12:52"
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.email "rene.klacan@gmail.com"
              git config --global user.name "Rene Klacan (CI)"
              git add -f dist
              git commit -m "Deployment: Add dist folder"
              git push -f heroku master
            fi
